server:
  servlet:
    contextPath: /AUTH_API
  port: 8087
kai:
  name: Auth_API
  key: authq51klfoni1ezxl5f2ckpfx248
  threadName: AUTH_API_NAME
  pollSize: 100
  error:
    code999: "Internal Server Error {0}"
    code998: "Timeout {0}"
    code701: "API not exist"
    code700: "API key not exists"
    code804: "Request lacks valid information"
    code803: "RequestId not exist"
    code996: "Error insert request to DB#{0}"
    code702: "API {0} not exist"
    code703: "Enquiry not exist"
    code704: "username {0} not exist"
    code705: "password {0} not exactly"
    code706: "MISSING FIELD{0}"
    code800: "Error create sessionId"
    code801: "Session {0} not exist"
    code802: "Error retrieving sessionId: {0}"
    code810: "Session {0} has expired"
    code605: "Input OTP is invalid"

spring:
  application:
    name: AUTH_API
  database:
    postgres: true
  postgredatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://14.225.254.212:5432/KAI_API?currentSchema=auth_api
    username: auth_api
    password: auth@kaiasia
    maximum-pool-size: 50
    idleTimeout: 120000
    minimumIdle: 10
  jpa:
    show-sql: false
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: http://14.225.254.212:8761/eureka

dbinfo:
  apiRequest: request_in
  apiResponse: request_out

dep-api:
  t24utilsApi:
    apiName: T24_UTIL_API
#    url: http://14.225.254.212:8082/T24_UTIL_API/process #api
    url: http://localhost:8082/T24_UTIL_API/process #api
    timeout: 60000 #milisecond
    apiKey: VDI0X1VUSUxfQVBJ

sessionTime:
  valid-duration: 3600 # 3600se
